### ISSUE TITLE
Add support for disabled line on more components

### ISSUE THREAD

**Issue by diogotcorreia** [diogotcorreia/Triton#20]
With messages, you can write `[lang]disabled.line[/lang]` (assuming you've set that as the message on config) and it won't send that message.

That should also work fine on anything else.

Progress:
- [x] Chat
- [x] Items
- [x] Action bars
- [x] Titles/Subtitles
- [ ] Scoreboards
- [x] Tab header/subheader
- [x] Bossbars
- [x] GUI titles
- [x] Entities
- [x] Custom TABs
- [x] Kick

Requester: @Helomi#9742 via #feature-requests on Discord

**Comment by Rexcantor** [comment]
Current status:

- If you send any disabled line placeholder in an action bar, that action bar won't be sent.
- If you send any disabled line placeholder in an item name, the item will have the default Minecraft name in the receiver's language, for example, `Block of Diamond`.
- If you send any disabled line placeholder in an item lore, that line will be removed from the lore.
- If you send any disabled line placeholder in a title, neither the title nor the subtitle will be sent (this is a Minecraft restriction).
- If you send any disabled line placeholder in a subtitle, only the subtitle won't be sent; the title will be sent as normal.

More will be added soon.

**Comment by diogotcorreia** [comment]
Due to issue #81, support for all message types has been added (except for scoreboards, which will be deprecated in v2.5.1).

Here is how disabled line works in various message types (keep in mind that the message just needs to contain _one_ disabled line placeholder for it to be treated as such):

- Chat: the message isn't sent and there isn't any visual indication of that message on the client. It behaves as if that message never existed.
- Actionbar: same as chat, with the pro that it doesn't even hide the current actionbar if there is one.
- Items titles: the client will see the default item material name (in their client locale) instead of the custom display name (e.g. `Block of Diamond`).
- Item lores: the line containing the disabled line placeholder will be removed from the lore.
- Books: the page containing the placeholder is deleted.
- Titles and subtitles: If there is a disabled line placeholder in the title, neither the title nor the subtitle will be sent. If there is a disabled line placeholder in the subtitle, only the subtitle won't be sent. Like actionbars, it won't hide the current title/subtitle if there is one.
- Tab header/footer: The header/footer will be removed.
- Bossbars: The text of the bossbar will be blank.
- GUI titles: The title will be blank.
- Entities: Their display name will be hidden.
- Custom TABs: The display name of the entity will be swapped for the real entity name.
- Kick: The kick message will be blank.

Expect these changes to come in Triton v2.5.1.
