### ISSUE TITLE
Release the plugin on Songoda

### ISSUE THREAD

**Issue by diogotcorreia** [diogotcorreia/Triton#71]
It might be interesting to publish the plugin to the [Songoda Marketplace](https://www.songoda.com/).

**Comment by TheCoolOne123** [comment]
Is the plugin already added? Or are you not planning anymore?

**Comment by diogotcorreia** [comment]
@TheCoolOne123 Yeah, the plugin is already up. It's still on 2.4.1, but if someone buys it I'll update. I haven't closed this because I'm waiting on Songoda to fix their BBCode editor since it completely breaks my plugin description.
https://www.songoda.com/marketplace/product/triton-translate-your-server.223

**Comment by TheCoolOne123** [comment]
@diogotcorreia 
If you want, I could help with that. I've used the BBCode editor myself. And I am able to recreate your plugin page on there. (This all done thru the Teams module from Songoda)

**Comment by diogotcorreia** [comment]
The plugin is now available in the [Songoda marketplace](https://www.songoda.com/marketplace/product/triton-translate-your-server.223)
