### ISSUE TITLE
Console log message translation

### ISSUE THREAD

**Issue by Shadow192** [diogotcorreia/Triton#75]
**Is your feature request related to a problem? Please describe.**

If it's possible will be nice if the console log message will be replaced with the default translation language.

**Additional context**
https://sfy.cx/sd/u/46685d.png

**Comment by ColaIan** [comment]
![image](https://user-images.githubusercontent.com/43201383/75090821-cca9d800-55a1-11ea-8eee-d7f4489d908b.png)
I agree with this suggestion, another additional context attached.

**Comment by diogotcorreia** [comment]
Added. It will be available in 2.6.0.
