### ISSUE TITLE
Some colors code are not working properly

### ISSUE THREAD

**Issue by Shadow192** [diogotcorreia/Triton#76]
**Describe the bug**
Some color codes are not working at all like '&r' and the Minecraft GUI color is changed to white.

**To Reproduce**
1. Try to name a gui &nNavigator and you'll see that the color has changed to white insteand of staying at a light gray ( which is lighter than &7 ).
2. '&r' is not working at all. Try to use magic color code and after the magic use &r and magic still continue.

**Screenshots (optional)**
https://sfy.cx/sd/u/d55bad.png

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.8.8 ( viaversion installed )
 - Client Minecraft Version 1.12.2
 - BungeeCord (specify if it's a fork) yes, waterfall
 - Triton Version: latest, 2.5.0

**Comment by diogotcorreia** [comment]
Found the issue.
A fix was found for 1.9+, but 1.8 clients don't get colors on any GUI titles with that "fix". So there is still work to do.

**Comment by diogotcorreia** [comment]
This issue is supposed to be resolved, but more testing still needs to be done to ensure it's behaving correctly in all MC versions.
A fix will be available in 2.5.1.

**Comment by diogotcorreia** [comment]
OP says this still hasn't been fixed for `§nNavigator`

**Comment by diogotcorreia** [comment]
Fixed. Will be available in 2.6.2.
