### ISSUE TITLE
Unknown NullPointer Occurred : (

### ISSUE THREAD

**Issue by ColaIan** [diogotcorreia/Triton#77]
**Describe the bug**
Triton dumped a nullpointer in the console, not sure what causes it.

**Server information (please complete the following information):**
 - Server Minecraft Version: [e.g. 1.8, 1.12, 1.14, etc...] 1.15.2
 - Client Minecraft Version (if using ViaVersion or something similar): [e.g. 1.8, 1.12, 1.14, etc...] 1.15.2
 - BungeeCord (specify if it's a fork) [yes or no] Yes, Waterfall
 - Triton Version: [e.g. 2.2.1, etc...] 2.5.0

**Additional context**
https://hastebin.com/utolojoyex.rb

**Comment by ColaIan** [comment]
https://hastebin.com/ewezeluqed.rb

Additional context:
Related to Neznamy's TAB plugin

**Comment by diogotcorreia** [comment]
This has been fixed and will be available in Triton v2.5.1.
