### ISSUE TITLE
disabled.line not working.

### ISSUE THREAD

**Issue by download042** [diogotcorreia/Triton#81]
Latest version of triton.
Error in console: https://pastebin.com/YX2nSN7e
CFG: http://prntscr.com/r720fz
chat: http://prntscr.com/r720ky

Paper 1.15.2
Latest protocol lib

ty for fix. :)

**Comment by download042** [comment]
My whole config, to be sure everything is right.
https://pastebin.com/AhDXWvz8

**Comment by diogotcorreia** [comment]
Interestingly enough, I'm pretty sure this hasn't been working since v1.0.0.
I was able to reproduce it.

**Comment by diogotcorreia** [comment]
This has been fixed (see #20) and will be available in v2.5.1.
