### ISSUE TITLE
Menu display is incorrect in TWIN

### ISSUE THREAD

**Issue by ethernetcat** [diogotcorreia/Triton#84]
**Describe the bug**
"Add Item" is displayed as "Sort by"

**To Reproduce**
Open the Twin and reduce the width.

**Expected behavior**
This should be labeled "Add Item".

**Screenshots**
![twin](https://user-images.githubusercontent.com/6961187/75984773-5f496000-5f2e-11ea-9602-dcb91a0c6bb5.PNG)

**Additional context**
I don't think that server-related information is needed for this, so I'll skip it.

`<span class="MuiTypography-root MuiListItemText-primary MuiTypography-body1">Sort by</span>`

**Comment by diogotcorreia** [comment]
Fixed
