### ISSUE TITLE
Getting disconnected when sending translated hovarable/clickable chat messages via ChatControlPro

### ISSUE THREAD

**Issue by download042** [diogotcorreia/Triton#92]
Paper 1.15.2
Latest protocol lib
Latest version of triton.
Latest chatcontrol etc

Actually no errors in console.

https://pastebin.com/7NNiQCjp

After unloading Triton, u can send chat messages without getting disconnected: 

![image](https://user-images.githubusercontent.com/13710574/76419609-e4a29980-63a0-11ea-8b6d-bd099b08f018.png)
![image](https://user-images.githubusercontent.com/13710574/76419617-eb311100-63a0-11ea-901d-049885397b07.png)

**Comment by diogotcorreia** [comment]
Fixed. Will be available in 2.6.2.
