### ISSUE TITLE
Chat Link issue

### ISSUE THREAD

**Issue by Emrolehero** [diogotcorreia/Triton#96]
Hi, with Triton i can't click on links wich don't end with .com (For exemple i have the dynmap link: http://178.33.5.19:25566/) but it don't work when I click on the link in game chat.
![image](https://user-images.githubusercontent.com/56135028/77021195-676dba80-6986-11ea-92ee-13a26d2b16a1.png)

**Comment by Emrolehero** [comment]
It works with other links like discord.gg, but not with the link http://178.33.5.19:25566

![image](https://user-images.githubusercontent.com/56135028/77024665-63926600-698f-11ea-9b8b-1f6740b5303c.png)

**Comment by diogotcorreia** [comment]
This has been fixed. It will be available in 2.6.3.
